<a href="https://colab.research.google.com/github/GiaBach12/Thuchanhtoancc/blob/main/Ch%C6%B0%C6%A1ng_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Thực hành 1: Lặp để tìm nghiệm**

In [27]:
x = 3 
print (x) 

3


In [28]:
import math
x = math.sqrt(1+x) 
print (x)

2.0


In [29]:
import math
x = math.sqrt(1+x) 
print (x)

1.7320508075688772


In [30]:
import math
x = math.sqrt(1+x) 
print (x)

1.6528916502810695


In [31]:
import math
x = math.sqrt(1+x) 
print (x)

1.6287699807772333


#**Thực hành 2: Lặp bằng while để tìm nghiệm**

In [32]:
import math 
x = 3 
lap = 1 
while (x != math.sqrt(x+1)): 
 x = math.sqrt(x+1) 
 lap = lap +1 

In [33]:
x

1.618033988749895

In [34]:
lap


32

#**Thực hành 3: Giải phương trình bằng hàm solve trong sympy**

In [53]:
import sympy as sp 
from sympy import Symbol 
x = Symbol('x') 
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

#**Thực hành 4: Các phép toán trên vector **

In [36]:
import numpy as np 
v1 = np.array([1., 2., 3.]) # tạo vector 3 chiều 
v2 = np.array([2., 1., 0.]) # cộng vector
v3 = v1 + v2 
v3


array([3., 3., 3.])

In [37]:
3*v1 + 2*v2

array([7., 8., 9.])

In [38]:
 [1, 2, 3] + [2, 1, 0] 
 

[1, 2, 3, 2, 1, 0]

In [39]:
3*[1, 2, 3] + 2*[2, 1, 0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

**Ghép nối (Concatenating) 2 hoặc nhiều vector: **

In [40]:
 v4 = np.hstack([v1, v2])
 v4

array([1., 2., 3., 2., 1., 0.])

**Phép nhân vô hướng 2 vector:**

In [41]:
np.dot(v1, v2)

4.0

**Tính toán giá trị sin của vector: **

In [42]:
angles = np.linspace(0, np.pi/2, 5) 
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [43]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

**hàm xử lý sin trong gói sympy sẽ không hỗ trợ việc tính toán trên toàn bộ vector chứa dữ liệu. Thử nghiệm: **

In [45]:
import sympy as sy 
sy.sin(angles) 

AttributeError: ignored

**viết một đoạn chương trình lặp với vector mới được xây dựng sẵn tạm thời: **

In [46]:
from sympy import sin as sysin 
angles = np.linspace(0, np.pi/2, 5) 
sinangle = np.zeros(5) # tương đương >>> sinangle = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) 
len(angles) # kiểm tra kích thước/số chiều của vector angles. 
for i in range(len(angles)): 
 sinangle[i] = sysin(angles[i]) # lưu ý: ở đây phải enter 2 lần để thoát khỏi vòng for. 
sinangle 

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

**Thực hành 5: Tính tổng các tích giữa ma trận và vector. Giả định gói thư viện numpy được đưa vào hệ thống có tên là np. Dạng:**

In [47]:
import numpy as np 
goc = np.pi/3 
A = np.array([ [np.cos(goc), -np.sin(goc)], 
             [np.sin(goc), np.cos(goc)] ]) 
V = np.array([1. , 0. ]) 
Y = np.dot(A, V) 
Y

array([0.5      , 0.8660254])

Lưu ý 1: Tích ma trận với vector hoặc ma trận cần lưu ý đến thứ tự. 
* Lưu ý 2: Không nên sử dụng dấu * thay cho phép toán dot. Vì dấu * sẽ tính toán tích tại từng 
phần tử (elementwise) của mảng/ma trận thay cho phép nhân ma trận được định nghĩa trong toán 
học. 
* Lưu ý 3: Một số dạng toán học và lệnh tương ứng trong Python 
- Tích vector - vector:  = ∑ 
 ↔  = . (, ). 
- Tích ma trận – ma trận:  = ∑"!"#" ↔  = . (!, #). 
- Tích vector - ma trận:  = ∑ ! ↔  = . (, !).

**Thực hành 6: Tính toán đạo hàm trên 1 vector dữ liệu **

#Trường hợp dx cố định: 

In [48]:
from numpy import diff 
dx = 0.1 
y = [1, 2, 3, 4, 4, 5, 6] 
dy = diff(y)/dx 
dy

array([10., 10., 10.,  0., 10., 10.])

In [49]:
z = np.array([1, 2, 3, 4, 4, 5, 6]) 
dz = diff(z)/dx 
dz 

array([10., 10., 10.,  0., 10., 10.])

 #Trường hợp dx là một dãy số:

In [50]:
from numpy import diff 
x = [.1, .2, .5, .6, .7, .8, .9] 
y = [1, 2, 3, 4, 4, 5, 6] 
dydx = diff(y)/diff(x) 
print (dydx)

[10.          3.33333333 10.          0.         10.         10.        ]


#**Thực hành 7: Một số hàm xử lý phẳng (không gian Euclide) **


In [51]:
from sympy.geometry import * 

# Tạo các điểm P1, P2, P3 và P4 

In [52]:
P1 = Point(0, 0) 
P2 = Point(3, 4) 
P3 = Point(2, -1) 
P4 = Point(-1, 5)

# Tạo 2 đoạn đường S1 và S2: 

In [54]:
S1 = Segment(P1, P2) 
S2 = Segment(P3, P4) 

#Kiểm 3 điểm thẳng hàng: 

In [55]:
Point.is_collinear(P1, P2, P3)

False

Độ dài của đoạn đường S1 

In [56]:
S1.length

5

 #Lấy trung điểm của đoạn 2: 

In [57]:
S2.midpoint

Point2D(1/2, 2)

Tính độ dốc của đường S1

In [58]:
S1.slope 

4/3

# Tìm vị trí giao nhau giữa hai đoạn đường

In [59]:
S1.intersection(S2) 

[Point2D(9/10, 6/5)]

# Góc giữa hai đoạn đường

In [60]:
Segment.angle_between(S1, S2) 

acos(sqrt(5)/5)

# Kiểm đoạn đường S1 có chứa điểm P3 hay không?

In [61]:
 S1.contains(P3)

False

# Lập và xem phương trình đường thẳng L1 đi qua 2 điểm P1 và P2:

In [62]:
L1 = Line(P1, P2) 
L1.equation() 

-4*x + 3*y

# Kiểm tính song song: 

In [63]:
L1.is_parallel(S1)

True

In [64]:
L1.is_parallel(S2)

False